### ISSUE TITLE
Discussion: "Know Thy Self" Content Piece

### ISSUE THREAD

**Issue by DanM3rcurius** [SecretDecks/Contentwriting#2]
**DISCUSSION**

1. I'd like to change the first sentence of the "ending" paragraph. Add more inquiring stress by placing the **"But why"** at the beginning? -> _"But why since the beginning of thought [...]_

2. add "(latin for Know Thyself)" to this sentence in line 43: "[...]the Wachowskis included temet nosce _"insert here"_ above the Oracle’s door, giving a nod to the Ancient Greeks.[...]

**Comment by DanM3rcurius** [comment]
@evolayak please let me know what you think of the proposed edits.
By the way your editing is incredible! Thank you so much!!!

**Comment by evolayak** [comment]
1. Change made
2. term added and I put the Latin phrase in italics, as well as the Greek phrase earlier on - clearer for the reader.

**Comment by DanM3rcurius** [comment]
feedback from townhall meeting (19th May) to be found [here](https://github.com/SecretDecks/Contentwriting/discussions/5)
all edits already done.
