### ISSUE TITLE
SecretDecks "Arcana" GitBook

### ISSUE THREAD

**Issue by stephen-rowan** [SecretDecks/Contentwriting#33]
## SecretDecks "Arcana" GitBook

Hi @DanM3rcurius and @wlstylr - I have started putting together a GitBook transcribing the DAO Brainstorming material to a good old linear format. I will send you edit access links by DM.

### The Backend GitBook Repo (Do not alter !)
https://github.com/SecretDecks/Arcana

### The Live GitBook
https://secretdecks.gitbook.io/arcana/

**Comment by DanM3rcurius** [comment]
Thanks for setting this up @stephen-rowan - will close this issue now.
